"""
"""

ALL_SPECIES = [ 'Stenotrophomonas_pavanii',
                'Klebsiella_pneumoniae',
                'Salmonella_enterica',
                'Pseudomonas_aeruginosa',
                'Morganella_morganii',
                'Moraxella_lincolnii',
                'Klebsiella_variicola',
                'Klebsiella_quasipneumoniae',
                'Haemophilus_parainfluenzae',
                'Escherichia_marmotae',
                'Escherichia_coli',
                'Enterobacter_kobei',
                'Comamonas_kerstersii',
                'Citrobacter_koseri',
                'Citrobacter_freundii',
                'Burkholderia_cenocepacia',
                'Acinetobacter_ursingii',
                'Acinetobacter_nosocomialis',
                'Klebsiella_aerogenes',
                'Acinetobacter_baumannii',
                'Staphylococcus_aureus',
                'Shigella_sonnei',
                'Serratia_marcescens',
                'Haemophilus_haemolyticus',
                'Acinetobacter_pittii',
                'Stenotrophomonas_maltophilia',
                'Lambda_phage',
                'Homo_sapiens' ]